# Generated by Django 6.0.5 on 2026-08-26 18:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_area', models.CharField(help_text='Ex: Lote Sul, Fazenda Boa Esperança', max_length=100)),
                ('tamanho_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coordenadas_gps', models.CharField(blank=True, help_text='Lat, Long', max_length=100, null=True)),
                ('tipo_cultura', models.CharField(help_text='Ex: Milho, Soja, Tomate', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('tipo_plano', models.CharField(choices=[('GRATUITO', 'Gratuito (com Ads)'), ('ASSINATURA', 'Assinatura Premium'), ('PERSONALIZADO', 'Infraestrutura Personalizada')], default='GRATUITO', max_length=15, verbose_name='Tipo de Plano')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeteccaoDoencaNutricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_deteccao', models.DateTimeField(auto_now_add=True)),
                ('imagem_analisada', models.ImageField(blank=True, null=True, upload_to='analises_plantas/')),
                ('resultado_machine_learning', models.CharField(help_text='Doença ou deficiência detectada', max_length=255)),
                ('grau_severidade', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], max_length=10)),
                ('status_tratamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRATAMENTO', 'Em tratamento'), ('RESOLVIDO', 'Resolvido')], default='PENDENTE', max_length=15)),
                ('area_plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes_doencas', to='core.areaplantio')),
            ],
        ),
        migrations.CreateModel(
            name='GestaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('tipo_movimentacao', models.CharField(choices=[('CUSTO_PREVISTO', 'Custo Previsto'), ('CUSTO_REAL', 'Custo Real'), ('RECEITA_ESTIMADA', 'Receita Estimada'), ('RECEITA_REALIZADA', 'Receita Realizada')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField(help_text='Ex: Compra de fertilizante XYZ, Venda da safra de milho')),
                ('area_plantio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_financeiras', to='core.areaplantio')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoramentoClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='Graus Celsius', max_digits=5)),
                ('umidade', models.DecimalField(decimal_places=2, help_text='Porcentagem', max_digits=5)),
                ('precipitacao_chuva', models.DecimalField(decimal_places=2, help_text='Milímetros (mm)', max_digits=8)),
                ('alertas_risco', models.CharField(blank=True, help_text='Ex: Risco de Geada, Seca Extrema', max_length=255, null=True)),
                ('area_plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos_climaticos', to='core.areaplantio')),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_plano', models.CharField(choices=[('GRATUITO', 'Gratuito (com Ads)'), ('ASSINATURA', 'Assinatura Premium'), ('PERSONALIZADO', 'Infraestrutura Personalizada')], default='GRATUITO', max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produtor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contato', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('FEEDBACK', 'Feedback da Plataforma'), ('SUPORTE', 'Pedido de Suporte'), ('TREINAMENTO', 'Solicitação de Treinamento')], max_length=15)),
                ('descricao', models.TextField()),
                ('avaliacao_impacto', models.PositiveSmallIntegerField(blank=True, help_text='Nota de 1 a 5 sobre o impacto positivo na produção', null=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.produtor')),
            ],
        ),
        migrations.AddField(
            model_name='areaplantio',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_plantio', to='core.produtor'),
        ),
        migrations.CreateModel(
            name='RecursoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_recurso', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INSUMO', 'Insumo (Semente, Fertilizante, Defensivo)'), ('MAQUINARIO', 'Maquinário'), ('MAO_DE_OBRA', 'Mão de Obra')], max_length=15)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, help_text='Qtd em kg, litros, ou unidades', max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.produtor')),
            ],
        ),
    ]
