# Generated by Django 6.0.5 on 2026-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Sementes', 'Sementes'), ('Fertilizantes', 'Fertilizantes'), ('Defensivos', 'Defensivos'), ('Ração animal', 'Ração animal'), ('Insumos veterinários', 'Insumos veterinários'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('unidade_medida', models.CharField(choices=[('und', 'Unidade (und)'), ('t', 'Tonelada (t)'), ('kg', 'Kilograma (kg)'), ('g', 'Grama (g)'), ('L', 'Litro (L)'), ('mL', 'Mililitros (mL)'), ('saca', 'Saca')], default='und', max_length=20)),
                ('estoque_atual', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('cultura', models.CharField(default='Diversas culturas', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nome'],
            },
        ),
    ]
