# Generated by Django 6.0.5 on 2026-05-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('contato', models.CharField(blank=True, help_text='Telefone, e-mail ou WhatsApp do fornecedor.', max_length=100, verbose_name='Contato')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
    ]
