# Generated by Django 6.0.5 on 2026-05-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (mL)'), ('un', 'Unidade (un)'), ('cx', 'Caixa (cx)'), ('pct', 'Pacote (pct)'), ('dz', 'Dúzia (dz)')], default='un', max_length=5, verbose_name='Unidade de medida')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade mínima antes de disparar alerta de ruptura.', max_digits=10, verbose_name='Estoque mínimo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nome'],
            },
        ),
    ]
