# Generated by Django 6.0.5 on 2026-05-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço por unidade do insumo (na unidade definida no cadastro do insumo).', max_digits=10, verbose_name='Preço')),
                ('prazo_entrega_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de entrega (dias)')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.fornecedor', verbose_name='Fornecedor')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_fornecedor', to='core.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Item de fornecedor',
                'verbose_name_plural': 'Itens de fornecedor',
                'ordering': ['fornecedor__nome', 'insumo__nome'],
                'unique_together': {('fornecedor', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='fornecedores', through='core.ItemFornecedor', to='core.insumo', verbose_name='Insumos disponíveis'),
        ),
    ]
