# Generated by Django 6.0.5 on 2026-05-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itemfornecedor_fornecedor_insumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade do insumo na receita (na unidade definida no cadastro do insumo).', max_digits=10, verbose_name='Quantidade')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_prato', to='core.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Item do prato',
                'verbose_name_plural': 'Itens do prato',
                'ordering': ['prato__nome', 'insumo__nome'],
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('ativo', models.BooleanField(default=True, help_text='Pratos inativos não aparecem no cardápio.', verbose_name='Ativo')),
                ('insumos', models.ManyToManyField(blank=True, related_name='pratos', through='core.ItemPrato', to='core.insumo', verbose_name='Insumos da receita')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='itemprato',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.prato', verbose_name='Prato'),
        ),
        migrations.AlterUniqueTogether(
            name='itemprato',
            unique_together={('prato', 'insumo')},
        ),
    ]
