# Generated by Django 6.0.5 on 2026-05-08 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_itemprato_prato_itemprato_prato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Sempre positiva. O sinal vem do tipo da movimentação (entrada soma, saída/desperdício subtrai).', max_digits=10, verbose_name='Quantidade')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_movimentacao', to='core.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Item da movimentação',
                'verbose_name_plural': 'Itens da movimentação',
                'ordering': ['movimentacao__data', 'insumo__nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('desperdicio', 'Desperdício'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.filial', verbose_name='Filial')),
                ('insumos', models.ManyToManyField(blank=True, related_name='movimentacoes', through='core.ItemMovimentacao', to='core.insumo', verbose_name='Insumos movimentados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='itemmovimentacao',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.movimentacao', verbose_name='Movimentação'),
        ),
    ]
