# Generated by Django 6.0.5 on 2026-05-08 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_filial_itemmovimentacao_movimentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
    ]
