# Generated by Django 6.0.5 on 2026-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_filial_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
