# Generated by Django 6.0.5 on 2026-05-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movimentacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.movimentacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data'],
            },
            bases=('core.movimentacao',),
        ),
    ]
