# Generated by Django 6.0.5 on 2026-05-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.movimentacao')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Valor total cobrado do cliente nesta venda.', max_digits=10, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data'],
            },
            bases=('core.movimentacao',),
        ),
    ]
