# Generated by Django 6.0.5 on 2026-05-08 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantos pratos foram vendidos.', verbose_name='Quantidade')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='core.prato', verbose_name='Prato')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='core.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da venda',
                'verbose_name_plural': 'Itens da venda',
                'ordering': ['venda__data', 'prato__nome'],
                'unique_together': {('venda', 'prato')},
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='pratos',
            field=models.ManyToManyField(blank=True, related_name='vendas', through='core.ItemVenda', to='core.prato', verbose_name='Pratos vendidos'),
        ),
    ]
