# Generated by Django 6.0.5 on 2026-05-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_itemvenda_venda_pratos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['-is_matriz', 'nome'], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato',
        ),
        migrations.AddField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Somente dígitos.', max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='filial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='filial',
            name='endereco',
            field=models.CharField(blank=True, help_text='Logradouro, número, bairro, CEP.', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='filial',
            name='is_matriz',
            field=models.BooleanField(default=False, help_text='Marque apenas em uma filial — a sede do grupo.', verbose_name='É matriz?'),
        ),
        migrations.AddField(
            model_name='filial',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Somente dígitos.', max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, help_text='Logradouro, número, bairro, CEP.', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ramo_alimenticio',
            field=models.CharField(choices=[('carnes', 'Carnes e frios'), ('hortifruti', 'Hortifruti'), ('mercearia', 'Mercearia'), ('laticinios', 'Laticínios'), ('bebidas', 'Bebidas'), ('bebidas_alcoolicas', 'Bebidas alcoólicas'), ('padaria', 'Padaria e confeitaria'), ('congelados', 'Congelados'), ('descartaveis', 'Descartáveis e embalagens'), ('limpeza', 'Higiene e limpeza'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Ramo alimentício'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='representante',
            field=models.CharField(blank=True, help_text='Pessoa de contato comercial.', max_length=150, verbose_name='Nome do representante'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome / Razão social'),
        ),
    ]
